basePath: /
definitions:
  api.DecryptRequest:
    properties:
      encryptedMessage:
        $ref: '#/definitions/models.EncryptedMessage'
      privateKey:
        type: integer
    type: object
  api.EncryptRequest:
    properties:
      message:
        type: string
      publicKey:
        type: integer
    type: object
  api.ReceiveMessagesRequest:
    properties:
      userId:
        type: string
    type: object
  api.SendMessageRequest:
    properties:
      encryptedMessage:
        $ref: '#/definitions/models.EncryptedMessage'
      receiverId:
        type: string
      senderId:
        type: string
    type: object
  models.ChatMessage:
    properties:
      content:
        $ref: '#/definitions/models.EncryptedMessage'
      senderId:
        type: string
    type: object
  models.EncryptedMessage:
    properties:
      c1:
        type: string
      c2:
        type: string
    type: object
  models.KeyPair:
    properties:
      privateKey:
        type: integer
      publicKey:
        type: integer
    type: object
  models.User:
    properties:
      id:
        type: string
      publicKey:
        type: integer
    type: object
host: localhost:3000
info:
  contact: {}
  description: Esta é uma API de servidor de chat simples.
  title: Chat API
  version: "1.0"
paths:
  /connect:
    post:
      consumes:
      - application/json
      description: Registra um novo usuário com seu ID e chave pública
      parameters:
      - description: Informações do usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Conecta um usuário ao servidor
      tags:
      - users
  /decrypt:
    post:
      consumes:
      - application/json
      description: Decripta uma mensagem usando a chave privada fornecida
      parameters:
      - description: Mensagem encriptada e chave privada
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.DecryptRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Decripta uma mensagem
      tags:
      - messages
  /encrypt:
    post:
      consumes:
      - application/json
      description: Encripta uma mensagem usando a chave pública fornecida
      parameters:
      - description: Mensagem e chave pública
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.EncryptRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EncryptedMessage'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Encripta uma mensagem
      tags:
      - messages
  /generate-keys:
    get:
      description: Gera e retorna um novo par de chaves pública e privada
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.KeyPair'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Gera um novo par de chaves
      tags:
      - keys
  /public-key/{userId}:
    get:
      description: Retorna a chave pública de um usuário específico
      parameters:
      - description: ID do usuário
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtém a chave pública de um usuário
      tags:
      - users
  /receive-messages:
    post:
      consumes:
      - application/json
      description: Retorna as mensagens encriptadas para um usuário específico
      parameters:
      - description: ID do usuário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.ReceiveMessagesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ChatMessage'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Recebe mensagens
      tags:
      - messages
  /send-message:
    post:
      consumes:
      - application/json
      description: Envia uma mensagem encriptada para um usuário específico
      parameters:
      - description: Mensagem encriptada e IDs de remetente e destinatário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.SendMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Envia uma mensagem
      tags:
      - messages
  /users:
    get:
      description: Retorna uma lista de IDs de todos os usuários conectados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Lista todos os usuários
      tags:
      - users
swagger: "2.0"
