basePath: /
definitions:
  handlers.CreateGroupRequest:
    properties:
      groupId:
        type: string
      members:
        description: Lista de userIds
        items:
          type: string
        type: array
      senderKey:
        description: Sender key em texto simples
        type: string
    required:
    - groupId
    - members
    - senderKey
    type: object
  handlers.EditGroupRequest:
    properties:
      members:
        description: Nova lista de userIds
        items:
          type: string
        type: array
      senderKey:
        description: Nova sender key em texto simples
        type: string
    type: object
  handlers.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handlers.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handlers.SendMessageRequest:
    properties:
      encryptedContent:
        $ref: '#/definitions/models.EncryptedMessage'
      recipientId:
        description: Pode ser userId ou groupId
        type: string
    required:
    - encryptedContent
    - recipientId
    type: object
  handlers.TokenResponse:
    properties:
      token:
        type: string
    type: object
  models.ChatMessage:
    properties:
      encryptedContent:
        $ref: '#/definitions/models.EncryptedMessage'
      id:
        type: integer
      recipientId:
        description: Identifica o destinatário (usuário ou grupo)
        type: string
      senderId:
        type: string
      timestamp:
        type: string
    type: object
  models.EncryptedMessage:
    properties:
      a:
        type: string
      b:
        type: string
    type: object
  models.Group:
    properties:
      createdAt:
        type: string
      groupId:
        type: string
      members:
        items:
          type: string
        type: array
      senderKey:
        description: Chave do remetente criptografada
        type: string
      updatedAt:
        type: string
    type: object
  models.PublicKey:
    properties:
      g:
        type: string
      p:
        type: string
      "y":
        type: string
    type: object
  models.User:
    properties:
      publicKey:
        $ref: '#/definitions/models.PublicKey'
      userId:
        type: string
      username:
        description: Nome de usuário
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Esta é uma API de servidor de chat simples.
  title: Chat API
  version: "1.0"
paths:
  /groups:
    post:
      consumes:
      - application/json
      description: Representa a requisição para criar um grupo
      parameters:
      - description: Dados do grupo
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateGroupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Grupos
  /groups/{groupId}:
    delete:
      consumes:
      - application/json
      description: Deleta um grupo e suas sender keys associadas
      parameters:
      - description: ID do grupo
        in: path
        name: groupId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Deletar um grupo
      tags:
      - Grupos
    put:
      consumes:
      - application/json
      description: Edita um grupo existente com novos membros e/ou nova sender key
      parameters:
      - description: ID do grupo
        in: path
        name: groupId
        required: true
        type: string
      - description: Dados do grupo
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/handlers.EditGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Editar um grupo
      tags:
      - Grupos
  /groups/update-sender-keys:
    post:
      consumes:
      - application/json
      description: Atualiza as sender keys para todos os membros do grupo
      parameters:
      - description: Dados do grupo
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/models.Group'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Atualizar sender keys
      tags:
      - Grupos
  /login:
    post:
      consumes:
      - application/json
      description: Representa a requisição de login
      parameters:
      - description: Dados do usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.TokenResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Autenticação
  /messages:
    get:
      consumes:
      - application/json
      description: Recupera todas as mensagens enviadas e recebidas pelo usuário autenticado
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ChatMessage'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Recuperar mensagens
      tags:
      - Mensagens
  /messages/send:
    post:
      consumes:
      - application/json
      description: Envia uma mensagem criptografada para um usuário ou grupo
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Dados da mensagem
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/handlers.SendMessageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Enviar uma mensagem
      tags:
      - Mensagens
  /register:
    post:
      consumes:
      - application/json
      description: Representa a requisição de registro
      parameters:
      - description: Dados do usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Autenticação
  /users/{userId}:
    get:
      consumes:
      - application/json
      description: Obtém os detalhes de um usuário específico
      parameters:
      - description: ID do usuário
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obter detalhes do usuário
      tags:
      - Usuários
    put:
      consumes:
      - application/json
      description: Atualiza informações de um usuário específico
      parameters:
      - description: ID do usuário
        in: path
        name: userId
        required: true
        type: string
      - description: Dados do usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Atualizar informações do usuário
      tags:
      - Usuários
  /ws:
    get:
      consumes:
      - application/json
      description: Estabelece uma conexão WebSocket para o usuário
      parameters:
      - description: ID do usuário
        in: query
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "101":
          description: Switching Protocols
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Conectar ao WebSocket
      tags:
      - WebSocket
schemes:
- http
swagger: "2.0"
