basePath: /
definitions:
  api.ReceiveMessagesRequest:
    properties:
      userId:
        type: string
    type: object
  api.SendMessageRequest:
    properties:
      encryptedMessage:
        properties:
          a:
            type: string
          b:
            type: string
        type: object
      receiverId:
        type: string
      senderId:
        type: string
    type: object
  models.ChatMessage:
    properties:
      content:
        type: string
      isRead:
        type: boolean
      senderId:
        type: string
      timestamp:
        type: string
    type: object
  models.PublicKey:
    properties:
      g:
        type: integer
      p:
        type: string
      "y":
        type: string
    type: object
  models.User:
    properties:
      publicKey:
        $ref: '#/definitions/models.PublicKey'
      userId:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Esta é uma API de servidor de chat simples.
  title: Chat API
  version: "1.0"
paths:
  /connect:
    post:
      consumes:
      - application/json
      description: Registra um novo usuário com seu ID e chave pública
      parameters:
      - description: Informações do usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Conecta um usuário ao servidor
      tags:
      - users
  /disconnect:
    post:
      consumes:
      - application/json
      description: Remove um usuário do servidor e seu histórico de chat
      parameters:
      - description: ID do usuário
        in: body
        name: userId
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Desconecta um usuário do servidor
      tags:
      - users
  /public-key/{userId}:
    get:
      description: Retorna a chave pública de um usuário específico
      parameters:
      - description: ID do usuário
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtém a chave pública de um usuário
      tags:
      - users
  /receive-messages:
    post:
      consumes:
      - application/json
      description: Retorna as mensagens encriptadas para um usuário específico
      parameters:
      - description: ID do usuário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.ReceiveMessagesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ChatMessage'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Recebe mensagens
      tags:
      - messages
  /send-message:
    post:
      consumes:
      - application/json
      description: Envia uma mensagem encriptada para um usuário específico
      parameters:
      - description: Mensagem encriptada e IDs de remetente e destinatário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.SendMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Envia uma mensagem
      tags:
      - messages
  /users:
    get:
      description: Retorna uma lista de IDs de todos os usuários conectados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Lista todos os usuários
      tags:
      - users
swagger: "2.0"
